// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHbYqRDj8fZaCJfcLhNbQtUdPY5MDi4Gw',
    appId: '1:953455322542:web:2965a1537774741b20543f',
    messagingSenderId: '953455322542',
    projectId: 'merotuktuk',
    authDomain: 'merotuktuk.firebaseapp.com',
    storageBucket: 'merotuktuk.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMa1Jsg4bTGPVdptErnvmLzuY_fyXTx8M',
    appId: '1:953455322542:android:b09d7e99e9184da720543f',
    messagingSenderId: '953455322542',
    projectId: 'merotuktuk',
    storageBucket: 'merotuktuk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiAYbiV7uBFg_6hj8GL39OrP4FF1B3Ios',
    appId: '1:953455322542:ios:e5da02518517cf6a20543f',
    messagingSenderId: '953455322542',
    projectId: 'merotuktuk',
    storageBucket: 'merotuktuk.appspot.com',
    iosBundleId: 'com.manoj.tuktuk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiAYbiV7uBFg_6hj8GL39OrP4FF1B3Ios',
    appId: '1:953455322542:ios:e5da02518517cf6a20543f',
    messagingSenderId: '953455322542',
    projectId: 'merotuktuk',
    storageBucket: 'merotuktuk.appspot.com',
    iosBundleId: 'com.manoj.tuktuk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHbYqRDj8fZaCJfcLhNbQtUdPY5MDi4Gw',
    appId: '1:953455322542:web:83f2650eb0b2b40920543f',
    messagingSenderId: '953455322542',
    projectId: 'merotuktuk',
    authDomain: 'merotuktuk.firebaseapp.com',
    storageBucket: 'merotuktuk.appspot.com',
  );
}
